#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Homebrew
#
# ****************************************************

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Autojump
# -> A cd command that learns
brew install autojump

# Bash & Bash Completion
brew install bash
brew install bash-completion

# Git
# -> Version control
brew install git

# Hub
# -> Command-line wrapper for git
brew install hub

# NVM
# -> Node Version Manager
brew install nvm

# MAS
# -> Mac App Store command-line interface
brew install mas

# Postgres
brew install postgres

# Python
brew install python

# Redis
# -> Advanced key-value store
brew install redis

# Image Magick
# -> Automate saving out image files
brew install imagemagick

# Mongo DB
# -> Database
brew install mongodb

# Remove outdated versions from the cellar
brew cleanup
