#!/usr/bin/env bash
# Install native apps

brew install caskroom/cask/brew-cask
brew tap caskroom/versions

brew cask install adobe-creative-cloud 2> /dev/null
brew cask install alfred 2> /dev/null
brew cask install anvil 2> /dev/null
brew cask install atom 2> /dev/null
brew cask install appcleaner 2> /dev/null
brew cask install dropbox 2> /dev/null
brew cask install evernote 2> /dev/null
brew cask install firefox 2> /dev/null
brew cask install google-chrome 2> /dev/null
brew cask install imageoptim 2> /dev/null
brew cask install iterm2 2> /dev/null
brew cask install keyboard-maestro 2> /dev/null
brew cask install mamp 2> /dev/null
brew cask install moom 2> /dev/null
brew cask install postgres 2> /dev/null
brew cask install spotify 2> /dev/null
brew cask install sublime-text3 2> /dev/null
